#!/bin/bash
#
# The following is basically taken from the LineageOS wiki:
# https://wiki.lineageos.org/devices/herolte/build

set -e
set -x

chronic apt-get install -y \
    android-tools-adb android-tools-fastboot

chronic apt-get install -y \
    bc bison build-essential ccache curl flex g++-multilib gcc-multilib git \
    gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev \
    liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev \
    libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
    xsltproc zip zlib1g-dev

chronic apt-get install -y openjdk-8-jdk

mkdir -p ~/bin
mkdir -p ~/android/lineage

curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo

PATH="$HOME/bin:$PATH"

cd ~/android/lineage
chronic repo init -u https://github.com/LineageOS/android.git -b cm-14.1

chronic repo sync

source build/envsetup.sh
breakfast herolte

# FIXME:
# "plug your existing S7 in via USB" - which is not possible on VM
./extract-files.sh

export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

croot
brunch herolte

# FIXME:
# having not set the variable, clearly the output is not in "cd $OUT"

