#!/bin/bash
#
# The following is basically taken from the LineageOS wiki:
# https://wiki.lineageos.org/devices/herolte/build

set -e
set -x

df -k

# travis hates it when you are quiet
# TODO - make this optional
echo "starting idle buster"
while sleep 9m; do echo -e "\\n=== IDLE BUSTER $SECONDS seconds ===\\n"; done &

chronic apt-get install -y \
    android-tools-adb android-tools-fastboot

chronic apt-get install -y \
    bc bison build-essential ccache curl flex g++-multilib gcc-multilib git \
    gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev \
    liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev \
    libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
    xsltproc zip zlib1g-dev

chronic apt-get install -y openjdk-8-jdk

mkdir -p ~/bin
mkdir -p ~/android/lineage

curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo

PATH="$HOME/bin:$PATH"

cd ~/android/lineage
chronic repo init -u https://github.com/LineageOS/android.git -b cm-14.1

mkdir -p .repo/local_manifests
cp local_themuppets.xml .repo/local_manifests/

chronic repo sync 2>&1 |tail -1000

source build/envsetup.sh

set +e
breakfast herolte
set -e

# FIXME:
#   ./extract-files.sh - possibly taken care of by themuppets repo above

export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

croot
brunch herolte

# FIXME:
# having not set the variable, clearly the output is not in "cd $OUT"

